export const GET_GALLERY = 'GET_GALLERY';
export const GET_GALLERY_PENDING = 'GET_GALLERY_PENDING';
export const GET_GALLERY_FULFILLED = 'GET_GALLERY_FULFILLED';
export const GET_GALLERY_REJECTED = 'GET_GALLERY_REJECTED';